name: secdart_analyzer_plugin
description: A plugin for the Dart Analyzer to provide a gradual security typing static analysis.
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.48.0 <3.0.0'

dependencies:
  analyzer: '0.32.4'
  plugin: '^0.2.0'
  analyzer_plugin: '0.0.1-alpha.4'
  secdart_analyzer:
    path: ../sec_analyzer


#dependency_overrides:
#  analyzer:
#    path: ../deps/sdk/pkg/analyzer
#  analyzer_plugin:
#    path: ../deps/sdk/pkg/analyzer_plugin
dev_dependencies:
  test: ^1.3.0
  test_reflective_loader: "^0.1.3"